export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'

export const GET_DATA_BEGIN = 'GET_DATA_BEGIN'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_ERROR = 'GET_DATA_ERROR'

export const CLEAR_ALERT = 'CLEAR_ALERT'
export const CLEAR_ALL_ALERTS = 'CLEAR_ALL_ALERTS'

export const CHANGE_DATA_TO_DISPLAY = 'CHANGE_DATA_TO_DISPLAY'

export const LOGOUT_USER = 'LOGOUT_USER'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS'

export const GET_ALL_SPECIES_SUCCESS = 'GET_ALL_SPECIES_SUCCESS'
export const GET_ALL_BREEDS_SUCCESS = 'GET_ALL_BREEDS_SUCCESS'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const SHOW_ALERT = 'SHOW_ALERT'

export const UPLOAD_DATA_BEGIN = 'UPLOAD_DATA_BEGIN'
export const UPLOAD_DATA_SUCCESS = 'UPLOAD_DATA_SUCCESS'
export const UPLOAD_DATA_ERROR = 'UPLOAD_DATA_ERROR'

export const CHANGE_REDIRECT_TO = 'CHANGE_REDIRECT_TO'

// export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS'
